name: Releases

on:
  push:
    branches:
      - main
    paths:
      - 'git_change_request/__init__.py'

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get current version
        run: |
          pip install -r test-requirements.txt
          echo "current_version=$(make show-version)" >> $GITHUB_ENV
          cat CHANGELOG.md | egrep -n "# Version" | awk -F ':' '{print $1}' | echo $(($(sed -n 2p)-3)) | xargs -d'\n' -I{} head -n {} CHANGELOG.md >> current_release.md
      - uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.current_version }}
          commit: ${{ github.sha }}
          bodyFile: "current_release.md"
          #Using my PAT because using the Github App Token does not support cascading triggering
          token: ${{ secrets.GIT_TOKEN }}